.eslintrc.js, .hound.yml, package-lock.json, package.json, src/components/exhibition/exhibition-device-group-view.tsx, src/components/exhibition/exhibition-room-view.tsx, src/components/exhibition/exhibition-settings-layout-edit-view.tsx, src/components/exhibition/exhibition-settings-page-edit-view.tsx, src/components/exhibition/exhibition-settings-view.tsx, src/components/exhibition/exhibition-view.tsx, src/components/exhibitions/exhibitions-view.tsx, src/components/generic/access-token-refresh.tsx, src/components/generic/basic-layout.tsx, src/components/generic/card-item.tsx, src/components/generic/error-dialog.tsx, src/components/generic/floor-plan.tsx, src/localization/strings.ts, src/reducers/auth.ts, src/reducers/exhibition.ts, src/types/index.ts
=> tslint fixes

src/components/preview/components/page-preview-component.tsx, src/components/preview/components/page-preview-media-view.tsx, src/components/preview/components/page-preview-player-view.tsx
=> Added support for previewing player and media components

src/components/exhibition/exhibition-settings-layout-edit-view.tsx, src/components/exhibition/exhibition-settings-page-edit-view.tsx, src/components/preview/components/page-preview-frame-layout.tsx, src/components/preview/components/page-preview-image-view.tsx
=> Hotfix 28 image improvements

src/components/dashboard/dashboard-devices-view.tsx, src/components/exhibition-v3/exhibition-view-v3.tsx, src/components/right-panel-editors/event-trigger-editor.tsx
=> Feature 38 eventtrigger and device editor

src/components/exhibition-v3/exhibition-view-v3.tsx, src/components/layout/layout-editor-view.tsx, src/components/preview/page-preview.tsx
=> Screen orientation support for preview

src/components/exhibition/exhibition-view.tsx, src/generated/client/models/ExhibitionDevice.ts, src/generated/client/models/ExhibitionPage.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Added support for adding new devices and moving pages between devices

src/components/exhibition/exhibition-view.tsx
Co-authored-by: Antti Leppä <antti.leppa@foyt.fi>
=> Fixes for issues creating pages

src/components/exhibition/exhibition-view.tsx
=> Fixed issue with page name editor

src/components/exhibition/exhibition-view.tsx, src/components/right-panel-editors/event-trigger-editor.tsx
=> Fixed issue #66

src/components/exhibition/exhibition-view.tsx
=> Added support for sorting pages

src/__tests__/basic.test.ts
=> Added scaling test to android stringToPx method

src/__tests__/basic.test.ts
=> Added more tests to android utils stringToPx

src/__tests__/basic.test.ts, src/utils/android-utils.ts
=> Added more tests to andoid utils

src/components/exhibition/exhibition-view.tsx
=> Changed navigate trigger event editor to list only device pages

package-lock.json, package.json, src/__tests__/basic.test.ts, src/components/preview/components/page-preview-flow-text-view.tsx, src/components/preview/components/page-preview-frame-layout.tsx, src/components/preview/components/page-preview-relative-layout.tsx, src/components/preview/components/page-preview-text-view.tsx, src/components/preview/components/page-preview-utils.ts, src/utils/android-utils.ts
=> Fixed issues from issue #81

package-lock.json, src/components/preview/components/page-preview-component.tsx, src/components/preview/components/page-preview-linear-layout.tsx, src/components/preview/components/page-preview-text-view.tsx
Resolves #85 
Co-authored-by: Tuomas Kämppi <tuomaskamppi@gmail.com>
=> Added linearlayout preview

src/components/right-panel-editors/event-trigger-editor.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
Also:
- Cleaned up code
- Unified change event methods
- Unified new event creation
- Added safety checks to all action type based render functions
=> Added devicegroupevent support

src/components/exhibition/exhibition-view.tsx, src/components/floor-plan/floor-plan-editor-view.tsx, src/components/generic/floor-plan-map.tsx, src/components/generic/polygon-dialog.tsx, src/components/left-middle-panel-editors/page-settings-editor.tsx, src/components/right-panel-editors/event-trigger-editor.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
Also:
- corrected event trigger titles
- removed redundant TreeView component
=> Support to remove selection in all selects in event trigger editor.

src/components/exhibition/exhibition-view.tsx
=> Fixed import

src/components/layout/layout-editor-view.tsx
=> Fixed codebuild errors

src/components/layout/layout-tree-menu.tsx, src/components/left-panel-editors/exhibition-tree-menu.tsx
=> removed toggle button from childless items

package-lock.json, src/components/layout/editor-components/color-picker.tsx, src/components/layout/editor-components/generic-property-select.tsx, src/components/layout/editor-components/generic-property-textfield.tsx, src/components/layout/editor-components/gravity-editor.tsx, src/components/layout/editor-components/layout-common-properties-editor.tsx, src/components/layout/editor-components/layout-widget-specific-properties-editor.tsx, src/components/layout/editor-components/widget-editors/text-view-editor.tsx, src/components/layout/editor-constants/keys.ts, src/components/layout/editor-constants/values.ts, src/components/layout/layout-editor-view.tsx, src/components/layout/layout-tree-menu.tsx, src/components/layout/utils/tree-data-utils.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styles/exhibition-tree-menu.ts, src/types/index.ts
Resolves #100 
Co-authored-by: Tuomas Kämppi <tuomaskamppi@gmail.com>
=> Added text view widget editor

src/components/exhibition/exhibition-view.tsx, src/components/left-middle-panel-editors/page-settings-editor.tsx, src/components/right-panel-editors/resource-editor.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/utils/resource-utils.ts
- removed ability to create new resources to page
- refactored resources to be identified by their index in page resources list
Resolves #97
=> Resources are now fetched from appropriate layout

src/components/layout/editor-components/generic-property-select.tsx, src/components/layout/editor-components/layout-widget-specific-properties-editor.tsx, src/components/layout/editor-components/widget-editors/button-editor.tsx, src/components/layout/editor-components/widget-editors/flow-text-view-editor.tsx, src/components/layout/editor-components/widget-editors/image-view-editor.tsx, src/components/layout/editor-components/widget-editors/linear-layout-editor.tsx, src/components/layout/editor-constants/keys.ts, src/components/layout/editor-constants/values.ts, src/components/layout/layout-tree-menu.tsx, src/components/layout/utils/tree-data-utils.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/types/index.ts
=> Feature 101 layout editor other view

src/components/exhibitions/exhibitions-screen.tsx, src/components/generic/card/card-item.tsx, src/components/generic/card/card-list.tsx, src/components/top-bar/top-bar.tsx, src/styles/basic-layout.ts, src/styles/card-item.ts, src/styles/exhibition-view.ts, src/styles/top-bar.ts
Tab and nav selection styles added, not implemented. Use by adding "selected" class for selected item according to opened view.
=> Header and card view styles

src/components/app.tsx, src/components/dashboard/dashboard-floor-plans-view.tsx, src/components/floor-plan/floor-plan-editor-view.tsx, src/components/generic/floor-plan-map.tsx, src/components/generic/top-bar.tsx, src/components/screens/content-versions-screen.tsx, src/components/screens/exhibition-content-rooms-screen.tsx, src/components/screens/group-content-versions-screen.tsx, tslint.json
=> Feature 127 generic map component

package-lock.json, package.json, src/components/app.tsx, src/components/floor-plan/floor-plan-tree-menu.tsx, src/components/generic/action-bar.tsx, src/components/generic/breadcrumbs.tsx, src/components/generic/file-uploader.tsx, src/components/generic/top-bar.tsx, src/components/screens/content-versions-screen.tsx, src/components/screens/floor-plan-screen.tsx, src/components/screens/floor-plans-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styles/components/floor-plan/floor-plan-tree-view.ts
Co-authored-by: Tuomas Kämppi <tuomaskamppi@gmail.com>
Resolves #128
=> Moved spaces view to v4 layout

src/components/layout/editor-components/color-picker.tsx, src/components/layout/editor-components/generic-property-select.tsx, src/components/layout/editor-components/generic-property-textfield.tsx, src/components/layout/editor-components/gravity-editor.tsx, src/components/layout/editor-components/layout-common-properties-editor.tsx, src/components/layout/editor-components/margin-padding-editor.tsx, src/components/layout/editor-components/widget-editors/flow-text-view-editor.tsx, src/components/layout/editor-components/widget-editors/text-view-editor.tsx, src/components/layout/layout-tree-menu.tsx, src/components/screens/layout-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styles/components/generic/color-picker.ts, src/styles/components/generic/element-settings-pane.ts, src/styles/components/layout-screen/gravity-editor.ts, src/styles/components/layout-screen/layout-editor-view.ts, src/styles/components/layout-screen/margin-padding-editor.ts, src/styles/theme.ts
=> Layout editor styles - scrolling issue fixed

src/components/screens/device-models-screen.tsx, src/components/screens/timeline-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
- also fixed breadcrumbs in page screen
- also added pixel dimensions flipping when creating
device model and its width is greater than height
=> Added page deletion

src/components/screens/device-models-screen.tsx
=> Fixed device settings fields

src/components/screens/layout-screen.tsx, src/components/screens/layouts-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Added layout deletion

src/components/generic/floor-plan-map.tsx
=> Added rfid antennas to device group area

src/components/floor-plan/floor-plan-tree-menu.tsx, src/components/generic/floor-plan-map.tsx, src/components/screens/floor-plan-screen.tsx
=> Multiple fixes for leaflet map

src/components/floor-plan/floor-plan-editor-view.tsx, src/components/generic/floor-plan-map.tsx, src/components/screens/floor-plan-screen.tsx
=> Fixed random zoom bug

src/actions/auth.ts, src/components/containers/access-token-refresh.tsx, src/components/layout/editor-components/generic-property-textfield.tsx, src/components/screens/layouts-screen.tsx
=> Fixed minor layout view bugs

src/components/generic/floor-plan-map.tsx, src/components/generic/top-bar.tsx, src/components/screens/floor-plan-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Fixed few leaflet bugs

src/components/screens/floor-plan-screen.tsx
=> Fixed floor adding bug

src/components/floor-plan/floor-plan-info.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Added antenna number

src/components/preview/components/page-preview-media-view.tsx, src/components/screens/floor-plan-screen.tsx, src/components/screens/layout-screen.tsx, src/components/screens/timeline-screen.tsx
=> Fixed broken breadcrumbs

src/components/floor-plan/floor-plan-info.tsx, src/components/preview/page-preview.tsx, src/components/screens/device-model-screen.tsx, src/components/screens/device-models-screen.tsx, src/components/screens/layout-screen.tsx, src/components/screens/layouts-screen.tsx, src/generated/client/models/DeviceModel.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Bugfix 185 device pixel sizes are wrong

src/components/floor-plan/floor-plan-crop.tsx, src/components/floor-plan/floor-plan-editor-view.tsx, src/components/screens/floor-plan-screen.tsx
=> Feature 192 improved crop tool

src/components/app.tsx, src/components/generic/device-list.tsx, src/components/generic/top-bar.tsx, src/components/screens/content-editor-screen.tsx, src/components/screens/timeline-screen.tsx, src/styles/content-editor-screen.ts
=> Made old timeline usable again

src/components/preview/components/page-preview-button.tsx, src/components/preview/page-preview.tsx, src/components/screens/layout-screen.tsx
=> Button width and height preview works

src/components/layout/editor-components/layout-common-properties-editor.tsx, src/components/layout/editor-components/layout-widget-specific-properties-editor.tsx, src/components/layout/utils/tree-data-utils.ts, src/components/screens/layout-screen.tsx, src/components/screens/sub-layout-screen.tsx
=> Fixed sublayout property editing problem

src/components/layout/layout-tree-menu.tsx, src/components/screens/layout-screen.tsx, src/components/screens/sub-layout-screen.tsx, src/styles/components/layout-screen/layout-editor-view.ts, src/styles/exhibition-tree-menu.ts
=> More space for treeview

src/components/screens/layout-screen.tsx, src/components/screens/sub-layout-screen.tsx
=> Added confirmation dialog to layout property delete

src/components/generic/polygon-dialog.tsx, src/components/layout/editor-components/layout-common-properties-editor.tsx, src/components/layout/editor-components/layout-widget-specific-properties-editor.tsx, src/components/layout/editor-components/margin-padding-editor.tsx, src/components/layout/layout-tree-menu.tsx, src/components/layout/utils/tree-data-utils.ts, src/components/layouts/element-contents-pane.tsx, src/components/layouts/element-hierarchy-pane.tsx, src/components/layouts/element-navigation-pane.tsx, src/components/layouts/element-properties-pane.tsx, src/components/right-panel-editors/event-trigger-editor.tsx, src/components/screens/content-editor-screen.tsx, src/components/screens/layout-screen.tsx, src/components/screens/sub-layout-screen.tsx, src/components/screens/timeline-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styles/content-editor-screen.ts, src/styles/element-contents-pane.ts, src/styles/element-properties-pane.ts, src/styles/element-timeline-pane.ts, src/utils/resource-utils.ts
=> Feature 218 button to event trigger listing

src/components/layout/editor-components/layout-common-properties-editor.tsx, src/components/layout/editor-components/widget-editors/button-editor.tsx, src/components/layout/editor-components/widget-editors/flow-text-view-editor.tsx, src/components/layout/editor-components/widget-editors/text-view-editor.tsx, src/components/preview/components/page-preview-button.tsx, src/styles/common-properties-editor.ts
=> Feature 220 layout editor preview text color doesnt work

src/components/containers/access-token-refresh.tsx, src/components/content-editor/timeline-devices-list.tsx, src/components/generic/device-list.tsx, src/components/screens/content-editor-screen.tsx
=> Added component for listing devices in timeline

package.json, src/components/content-editor/timeline-devices-list.tsx, src/components/content-editor/timeline-editor.tsx, src/components/screens/content-editor-screen.tsx, src/styles/components/content-editor/timeline-devices-list.ts, src/styles/components/content-editor/timeline-editor.ts, src/styles/content-editor-screen.ts, src/styles/element-timeline-pane.ts
=> Added page listing to timeline

src/components/content-editor/transitions-editor.tsx, src/components/screens/content-editor-screen.tsx
=> Transition editor is fixed

src/components/layout/editor-components/generic-property-checkbox.tsx, src/components/layout/editor-components/widget-editors/button-editor.tsx, src/components/layout/editor-constants/keys.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
Resolves #231 
Added support for:
button background color
button text gravity
button text caps
button background image
=> Layout editor: Multiple fixes and improvements

src/components/screens/content-editor-screen.tsx, src/utils/resource-utils.ts
=> Added support for editing multiple resources

src/components/preview/components/page-preview-frame-layout.tsx, src/components/preview/components/page-preview-text-view.tsx, src/utils/android-utils.ts
=> Text align gravity and other text alignments implemented

src/components/generic/spaces-map.tsx, src/components/screens/content-editor-screen.tsx, src/generated/client/models/ExhibitionDevice.ts, src/generated/client/models/ExhibitionPageResource.ts
=> Device page order now updates properly

src/components/layout/editor-components/generic-property-textfield.tsx, src/components/layout/editor-components/widget-editors/button-editor.tsx, src/components/layout/editor-components/widget-editors/flow-text-view-editor.tsx, src/components/layout/editor-components/widget-editors/image-view-editor.tsx, src/components/layout/editor-components/widget-editors/text-view-editor.tsx, src/components/layout/layout-tree-menu.tsx, src/components/layout/utils/tree-data-utils.ts, src/components/screens/content-editor-screen.tsx, src/components/screens/layout-screen.tsx
Resolves #245 
Added UUID to layout resources
Cleaned code
Added new utility function
=> Improved resource naming

src/components/content-editor/resource-editor.tsx, src/components/screens/content-editor-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
- also added "no events" text if no events are found in resource
resolves #247
=> Added scripted button and fixed some styles

src/components/app.tsx, src/components/floor-plan/floor-plan-editor-view.tsx, src/components/generic/top-bar.tsx, src/components/screens/content-editor-screen.tsx, src/components/screens/content-versions-screen.tsx, src/components/screens/device-model-screen.tsx, src/components/screens/group-content-versions-screen.tsx, src/components/screens/rooms-screen.tsx, src/components/screens/timeline-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
Also hid old timeline and removed "v4" from paths
resolves #249
=> Feature 249 support for adding pages in new timeline

src/components/content-editor/timeline-editor.tsx, src/components/screens/content-editor-screen.tsx, src/localization/strings.ts
=> Feature 252 assign device index page id automatically

src/components/content-editor/common-settings-editor.tsx, src/components/content-editor/event-trigger-editor.tsx, src/components/content-editor/page-transition-elements-editor.tsx, src/components/content-editor/resource-editor.tsx, src/components/content-editor/timeline-devices-list.tsx, src/components/content-editor/transitions-editor.tsx, src/components/layouts/element-contents-pane.tsx, src/components/layouts/element-properties-pane.tsx, src/components/screens/content-editor-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styles/element-contents-pane.ts, src/styles/element-navigation-pane.ts, src/styles/element-properties-pane.ts, src/styles/theme.ts
=> timeline common themes and style

src/components/content-editor/common-settings-editor.tsx, src/components/layout/layout-tree-menu.tsx, src/components/layouts/element-hierarchy-pane.tsx, src/components/layouts/element-navigation-pane.tsx, src/components/layouts/element-settings-pane.tsx, src/components/screens/layout-screen.tsx, src/styles/exhibition-tree-menu.ts, src/styles/theme.ts
=> Hotfix 258 panel width issue

src/components/app.tsx, src/components/generic/device-list.tsx
=> New timeline button removed

src/components/content-editor/constants.ts, src/components/content-editor/tabs-editor.tsx, src/components/layout/editor-components/generic-property-select.tsx, src/components/layout/editor-components/generic-property-switch.tsx, src/components/layout/editor-components/gravity-editor.tsx, src/components/layout/editor-components/widget-editors/tab-layout-editor.tsx, src/components/layout/editor-constants/keys.ts, src/components/layout/editor-constants/values.ts, src/components/layout/utils/tree-data-utils.ts, src/components/preview/components/page-preview-button.tsx, src/components/preview/components/page-preview-flow-text-view.tsx, src/components/preview/components/page-preview-frame-layout.tsx, src/components/preview/components/page-preview-image-view.tsx, src/components/preview/components/page-preview-linear-layout.tsx, src/components/preview/components/page-preview-player-view.tsx, src/components/preview/components/page-preview-relative-layout.tsx, src/components/preview/components/page-preview-text-view.tsx, src/components/preview/page-preview.tsx, src/components/screens/content-editor-screen.tsx, src/generated/client/models/ExhibitionPageResourceType.ts, src/generated/client/models/PageLayoutWidgetType.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/utils/content-editor-utils.ts, src/utils/resource-utils.ts
=> Feature 244 layout editor tab support

src/components/layout/editor-components/generic-property-enabled-checkbox.tsx, src/components/layout/editor-components/layout-common-properties-editor.tsx, src/components/layout/editor-components/widget-editors/button-editor.tsx, src/components/layout/editor-constants/keys.ts, src/components/layout/utils/tree-data-utils.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Feature 257 move image background from button editor to common properties editor

src/components/layout/editor-components/layout-common-properties-editor.tsx, src/components/layout/editor-constants/keys.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Added elevation property

src/components/layout/layout-tree-menu.tsx, src/components/screens/layout-screen.tsx, src/components/screens/sub-layout-screen.tsx
=> Layout editor element deleting moved to right side panel

package-lock.json, package.json, src/components/content-editor/tabs-editor.tsx, src/components/generic/generic-dialog.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/types/ckeditor.d.ts
=> Feature 263 ckeditor

src/components/layout/editor-components/layout-common-properties-editor.tsx, src/components/layout/editor-components/widget-editors/tab-layout-editor.tsx, src/components/layout/editor-constants/keys.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Feature 270 layout editor selected tab indicator height property support

src/components/preview/components/page-preview-player-view.tsx, src/components/preview/page-preview.tsx
=> Video preview is visible and has controls now

package-lock.json, src/components/layout/editor-components/color-picker.tsx, src/components/layout/editor-components/layout-common-properties-editor.tsx, src/components/layout/editor-components/margin-padding-editor.tsx, src/components/layout/editor-components/widget-editors/button-editor.tsx, src/components/layout/editor-components/widget-editors/flow-text-view-editor.tsx, src/components/layout/editor-components/widget-editors/tab-layout-editor.tsx, src/components/layout/editor-components/widget-editors/text-view-editor.tsx, src/styles/common-properties-editor.ts, src/styles/components/generic/color-picker.ts
-also fix to margin padding editor styles
Resolves #277
=> Picker now closes when clicked outside of it

src/components/layout/editor-components/generic-property-select.tsx, src/components/layout/editor-components/generic-property-textfield.tsx, src/components/layout/editor-components/gravity-editor.tsx, src/components/layout/utils/tree-data-utils.ts
=> Added checks for emptying property value

src/components/screens/content-editor-screen.tsx
- also added couple missing "key" params
Resolves #281
=> Refactored component update logic

src/components/preview/components/page-preview-button.tsx
=> Added font size property support

src/components/preview/page-preview.tsx
=> Added preview support for margins and paddings

src/components/layout/layout-tree-menu.tsx, src/components/preview/components/page-preview-frame-layout.tsx, src/components/preview/components/page-preview-text-view.tsx
=> Bug 250 layout editors centering gravity doesnt work

src/components/preview/components/page-preview-component.tsx, src/components/preview/components/page-preview-frame-layout.tsx, src/components/screens/content-editor-screen.tsx, src/styles/components/generic/color-picker.ts, src/styles/content-editor-screen.ts, src/styles/element-contents-pane.ts, src/styles/theme.ts
=>  styles, removed unnecessary divs from preview

src/components/content-editor/timeline-editor.tsx, src/components/generic/spaces-map.tsx, src/components/left-middle-panel-editors/device-settings-editor.tsx, src/components/screens/content-editor-screen.tsx, src/components/screens/timeline-screen.tsx, src/generated/client/models/ExhibitionDevice.ts, src/generated/client/models/ExhibitionPage.ts, src/generated/client/models/ExhibitionPageEventActionType.ts, src/generated/client/models/VisitorSession.ts
=> Feature 294 support for localized page order

src/components/layouts/element-properties-pane.tsx, src/components/screens/content-editor-screen.tsx
=> Added on close click handler for properties pane

src/styles/components/content-editor/timeline-editor.ts, src/styles/content-editor-screen.ts, src/styles/theme.ts
- also made scroll bar styles global
Resolves #304
=> timeline now scrolls

src/components/screens/content-editor-screen.tsx
=> Event trigger list is now hidden when empty

package-lock.json, package.json, src/components/content-editor/tabs-editor.tsx, src/components/generic/generic-dialog.tsx, src/types/ckeditor.d.ts
=> Moved from CKEditor 5 to 4

src/components/content-editor/timeline-devices-list.tsx, src/components/content-editor/timeline-editor.tsx, src/components/screens/content-editor-screen.tsx, src/styles/components/content-editor/timeline-devices-list.ts, src/styles/content-editor-screen.ts
=> Timeline now contains language tabs for content

src/components/screens/device-models-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
Resolves #315 
All device display settings are now visible
Fixed touch switch type error
Removed old density calculation functions
=> All device display settings visible

src/components/screens/content-editor-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/utils/page-utils.ts
No issues found from tabs. The crashing issues was caused by old layout
Resolves #318
=> Fixed issue where content versions would come in random order

src/components/preview/components/page-preview-button.tsx, src/components/preview/components/page-preview-flow-text-view.tsx, src/components/preview/components/page-preview-frame-layout.tsx, src/components/preview/components/page-preview-image-view.tsx, src/components/preview/components/page-preview-linear-layout.tsx, src/components/preview/components/page-preview-player-view.tsx, src/components/preview/components/page-preview-relative-layout.tsx, src/components/preview/components/page-preview-text-view.tsx, src/components/preview/page-preview.tsx
=> Aligning should work perfectly once linear layout gravity is implemented

src/components/content-editor/constants.ts, src/components/content-editor/tabs-editor.tsx, src/components/generic/pan-zoom.tsx, src/components/generic/tab-item.tsx, src/components/layout/editor-components/layout-widget-specific-properties-editor.tsx, src/components/layout/editor-components/widget-editors/tab-layout-editor.tsx, src/components/layout/editor-constants/constants.ts, src/components/preview/components/page-preview-component.tsx, src/components/preview/components/page-preview-flow-text-view.tsx, src/components/preview/components/page-preview-frame-layout.tsx, src/components/preview/components/page-preview-linear-layout.tsx, src/components/preview/components/page-preview-material-tab.tsx, src/components/preview/components/page-preview-relative-layout.tsx, src/components/preview/page-preview.tsx, src/components/screens/content-editor-screen.tsx, src/components/screens/layout-screen.tsx, src/components/screens/sub-layout-screen.tsx, src/generated/client/models/PageLayoutView.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/utils/content-editor-utils.ts, src/utils/preview-utils.ts, src/utils/resource-utils.ts
=> Feature 320 tab component for preview

src/components/content-editor/constants.ts, src/components/content-editor/dynamic-resource-editor.tsx, src/components/content-editor/dynamic-resource-switch-when-list.tsx, src/components/content-editor/layout-view-resources-list.tsx, src/components/content-editor/media-library-button.tsx, src/components/content-editor/resource-editor.tsx, src/components/content-editor/tab-editor.tsx, src/components/content-editor/tabs-editor.tsx, src/components/right-panel-editors/media-library.tsx, src/components/screens/content-editor-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styles/components/content-editor/layout-view-resources-list.ts, src/styles/components/content-editor/resource-editor.ts, src/utils/generic-utils.ts, src/utils/resource-utils.ts
=> Feature 317 timeline resource and property editor clean up

src/components/content-editor/resource-editor.tsx, src/components/right-panel-editors/media-library.tsx
=> Fixed undefined/null check

src/components/screens/content-editor-screen.tsx
=> New page gets now selected content version id

src/components/content-editor/tab-editor.tsx, src/components/screens/content-editor-screen.tsx
=> Feature 334 tab media library

src/components/generic/pan-zoom.tsx, src/components/generic/tab-item.tsx, src/components/generic/tab-list.tsx, src/components/preview/components/page-preview-frame-layout.tsx, src/components/preview/components/page-preview-linear-layout.tsx, src/components/preview/components/page-preview-relative-layout.tsx, src/styles/components/generic/tab-item.ts
Also changed zoom multiplier value to percentages for clarity
Resolves #338
=> Added preview for all tab content types

src/components/content-editor/tab-editor.tsx, src/components/preview/components/page-preview-button.tsx, src/components/preview/components/page-preview-frame-layout.tsx, src/components/preview/components/page-preview-material-tab.tsx, src/components/preview/components/page-preview-text-view.tsx, src/components/preview/page-preview.tsx, src/components/screens/content-editor-screen.tsx, src/localization/en.json, src/localization/fi.json
=> Feature 340 multiple preview fixes

src/components/screens/exhibitions-screen.tsx
=> Removed set status option

src/components/content-editor/event-trigger-editor.tsx, src/components/screens/content-editor-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Added support for execute web script action

src/components/screens/content-editor-screen.tsx
=> Bugfix 354 page clicking and adding was crashing app

src/components/generic/file-uploader.tsx, src/components/right-panel-editors/media-library.tsx, src/components/screens/floor-plan-screen.tsx
=> File uploader supports multiple file upload

src/components/screens/content-editor-screen.tsx
=> Fixed issue #363

src/components/right-panel-editors/media-library.tsx, src/utils/file-upload.ts
=> Added support for uploading directly to S3

src/components/content-editor/constants.ts, src/components/content-editor/tab-editor.tsx, src/components/content-editor/timeline-devices-list.tsx, src/components/content-editor/timeline-editor.tsx, src/components/generic/tab-item.tsx, src/components/preview/components/page-preview-component.tsx, src/components/preview/components/page-preview-frame-layout.tsx, src/components/preview/components/page-preview-linear-layout.tsx, src/components/preview/components/page-preview-material-tab.tsx, src/components/preview/components/page-preview-relative-layout.tsx, src/components/preview/page-preview.tsx, src/components/screens/content-editor-screen.tsx, src/components/screens/visitor-variables-screen.tsx, src/generated/client/models/ExhibitionDevice.ts, src/generated/client/models/VisitorVariable.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styles/content-editor-screen.ts, src/styles/element-timeline-pane.ts, src/styles/theme.ts, src/utils/preview-utils.ts
=> Added feature

src/components/preview/components/page-preview-component.tsx, src/components/screens/layout-screen.tsx, src/generated/client/models/PageLayoutWidgetType.ts
=> Feature 376 visitor group creation view

src/api/api.ts, src/components/app.tsx, src/components/generic/with-debounce.tsx, src/components/screens/manage-visitor-session-variables-screen.tsx, src/components/screens/rooms-screen.tsx, src/components/screens/visitor-variables-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styles/screens/manage-visitor-session-variables-screen.ts
=> Feature 375 support for resetting user choices

src/components/generic/card/card-item.tsx, src/components/generic/card/card-list.tsx, src/components/group-content-version/group-content-versions-info.tsx, src/components/screens/content-versions-screen.tsx, src/components/screens/device-models-screen.tsx, src/components/screens/exhibitions-screen.tsx, src/components/screens/floor-plans-screen.tsx, src/components/screens/group-content-versions-screen.tsx, src/components/screens/layouts-screen.tsx, src/components/screens/rooms-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styles/components/generic/card/card-list.ts
=> Removed unfinished features from UI

src/components/generic/tag-listener.tsx
=> Fixed issue #385

src/components/generic/help-dialog.tsx, src/components/layout/editor-components/generic-property-checkbox.tsx, src/components/layout/editor-components/generic-property-enabled-checkbox.tsx, src/components/layout/editor-components/layout-common-properties-editor.tsx, src/components/layout/editor-components/widget-editors/button-editor.tsx, src/components/layout/editor-components/widget-editors/linear-layout-editor.tsx, src/components/layout/editor-components/widget-editors/tab-layout-editor.tsx, src/components/layout/editor-constants/values.ts, src/components/layout/layout-tree-menu.tsx, src/components/screens/layout-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styles/element-navigation-pane.ts
resolves #389 
Adds instructions to most used components in Layout editor. Will continue other views in another issue.
=> Feature 389 UI terminology update

src/components/content-editor/dynamic-resource-editor.tsx, src/components/content-editor/event-trigger-editor.tsx, src/components/content-editor/layout-view-resources-list.tsx, src/components/content-editor/transitions-editor.tsx, src/components/floor-plan/floor-plan-info.tsx, src/components/generic/help-dialog.tsx, src/components/screens/content-editor-screen.tsx, src/components/screens/floor-plans-screen.tsx, src/components/screens/group-content-versions-screen.tsx, src/components/screens/rooms-screen.tsx, src/components/screens/visitor-variables-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styles/components/content-editor/resource-editor.ts
=> Feature 392 UI terminology update part 2

src/components/screens/floor-plan-screen.tsx, src/generated/client/apis/ExhibitionDeviceGroupsApi.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Added support for copying device groups

src/components/floor-plan/floor-plan-info.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Added forced portrait option

src/components/content-editor/dynamic-resource-editor.tsx, src/components/content-editor/dynamic-resource-switch-when-list.tsx, src/components/content-editor/resource-editor.tsx, src/components/preview/components/page-preview-text-view.tsx, src/components/screens/content-editor-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Dynamic resource editor now uses exhibition user variables

package-lock.json, src/components/content-editor/event-trigger-editor.tsx, src/components/content-editor/page-event-dialog.tsx, src/components/generic/generic-dialog.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Feature 403 advanced events UI improvements

src/components/content-editor/event-trigger-editor.tsx, src/components/layout/editor-components/layout-widget-specific-properties-editor.tsx, src/components/layout/editor-components/widget-editors/touchable-opacity-editor.tsx, src/components/preview/components/page-preview-component.tsx, src/components/preview/components/page-preview-flow-text-view.tsx, src/components/preview/components/page-preview-frame-layout.tsx, src/components/preview/components/page-preview-linear-layout.tsx, src/components/preview/components/page-preview-relative-layout.tsx, src/components/preview/components/page-preview-text-view.tsx, src/components/preview/components/page-preview-touchable-opacity.tsx, src/components/right-panel-editors/media-library.tsx, src/generated/client/models/PageLayoutWidgetType.ts
- also fixed bugs and cleaned code
Resolves #406
=> Added touchable opacity support

src/components/content-editor/constants.ts, src/components/preview/components/page-preview-touchable-opacity.tsx, src/components/screens/content-editor-screen.tsx, src/styles/content-editor-screen.ts
- Also fixed event trigger deleting
=> Added touchable opacity to element list

src/components/generic/with-debounce.tsx, src/components/screens/content-versions-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styles/exhibition-view.ts
=> Added activity condition for content versions

src/components/content-editor/event-trigger-editor.tsx
=> Hopefully fixed event trigger editor

src/components/layout/editor-components/layout-widget-specific-properties-editor.tsx, src/components/layout/editor-components/widget-editors/player-view-editor.tsx, src/components/layout/editor-constants/keys.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Added support for video playback options

src/components/layout/editor-components/widget-editors/player-view-editor.tsx, src/components/layout/editor-constants/keys.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Added support for changing video auto-play delay

src/components/floor-plan/floor-plan-tree-menu.tsx, src/styles/floor-plan-editor-view.ts
=> fixed scrolling issue

src/components/generic/spaces-map.tsx, src/components/layout/editor-components/layout-common-properties-editor.tsx, src/components/layout/editor-components/layout-widget-specific-properties-editor.tsx, src/components/screens/floor-plan-screen.tsx, src/components/screens/layout-screen.tsx
=> Fixed save buttons on layout and floorplan screen

src/components/generic/confirm-dialog.tsx, src/components/screens/content-editor-screen.tsx, src/components/screens/content-versions-screen.tsx, src/components/screens/device-model-screen.tsx, src/components/screens/device-models-screen.tsx, src/components/screens/exhibitions-screen.tsx, src/components/screens/floor-plan-screen.tsx, src/components/screens/group-content-versions-screen.tsx, src/components/screens/layout-screen.tsx, src/components/screens/layouts-screen.tsx, src/components/screens/manage-visitor-session-variables-screen.tsx, src/components/screens/sub-layout-screen.tsx, src/components/screens/visitor-variables-screen.tsx, src/generated/client/apis/ExhibitionDevicesApi.ts, src/generated/client/apis/ExhibitionPagesApi.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/types/index.ts, src/utils/delete-utils.ts
=> Feature 421 improve delete functionalities

src/components/layout/editor-components/widget-editors/player-view-editor.tsx, src/components/layout/editor-constants/keys.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Added support for editing visible video control buttons on layouts

src/components/content-editor/common-settings-editor.tsx, src/components/content-editor/page-event-dialog.tsx
=> Feature 428 page sorting alphabetically

src/components/screens/visitor-variables-screen.tsx
=> Fixed issue #465

src/components/floor-plan/floor-plan-info.tsx, src/generated/client/models/ExhibitionDeviceGroup.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Feature 468 index page timeout

src/components/screens/content-editor-screen.tsx
=> Fixed issue #476

src/components/screens/exhibitions-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Feature 479 rename exhibition

src/constants/configuration.ts, src/mqtt/index.ts, src/types/index.ts
=> Added support for failover MQTT servers
